### ISSUE TITLE
add new troops and townhall

### ISSUE THREAD

**Issue by devsargam** [Statscell/clash-assets#5]
recently new troop electro titan and town hall 15 has been released.

**Comment by bsantosh909** [comment]
Hi @devsargam Thank you for mentioning.
I have been a little busy lately, but I will try to get those added as soon as possible 🙏

**Comment by devsargam** [comment]
@TheLearneer I'm quite free atm. I should be able to add those if you assign me. :smile:

**Comment by devsargam** [comment]
Forgot to mention new seize has also been added

**Comment by bsantosh909** [comment]
If you are well aware about how to get those assets, then sure, please go ahead and add it 👍

**Comment by devsargam** [comment]
@TheLearneer if there's a specific way on getting those assets then I might need some assistance.

**Comment by bsantosh909** [comment]
You might want to check this <https://github.com/Statscell/Dumpsc> repo

**Comment by devsargam** [comment]
@TheLearneer where can i find assets for new townhall. Searching for about an hour. :sloth:

**Comment by bsantosh909** [comment]
@devsargam The TH assets are a little bit tricky.
It isn't a single image but multiple smaller images attached together.

It might be tricky so you can leave those for now.
I will make sure to add them as soon as possible 🙏

**Comment by devsargam** [comment]
@TheLearneer thanks. Thoughts about adding a pets directory. There are already 8 of them.
